name: fjut_qcx
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2

  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.3.1+1
  # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.9
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.5
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.3
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: 0.2.6+1
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 5.4.1
  # 图片选择插件 https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.6.3+1
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.4
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 0.3.21
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.2.0
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.1.8+1
  # 城市选择列表 https://github.com/flutterchina/azlistview
  azlistview: ^0.1.2
  # 用于日历功能 https://github.com/apptreesoftware/date_utils
  # date_utils: ^0.1.0+2
  # 手势识别 https://github.com/aleksanderwozniak/simple_gesture_detector
  simple_gesture_detector: ^0.1.4
  # 曲线图表 https://github.com/aeyrium/bezier-chart
  # bezier_chart: ^1.0.7
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.6.1
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.0.0
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^4.0.2
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^4.0.4
  # 高德2D地图插件 https://github.com/simplezhli/flutter_2d_amap
  flutter_2d_amap:
    git:
      url: https://github.com/simplezhli/flutter_2d_amap.git
  # 扫码 https://github.com/apptreesoftware/flutter_barcode_reader
  barcode_scan:
    git:
      url: https://github.com/simplezhli/flutter_barcode_reader.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_model: ^0.0.2
  build_runner: ^1.0.0
  json_serializable: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/home/
    - assets/images/state/
    - assets/images/recruitment/
    - assets/images/login/
    - assets/images/goods/
    - assets/images/account/
    - assets/images/mine/
  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf

